name: Playwright Daily Test

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      #BASE_URL: ${{ secrets.BASE_URL }}
      CW_USERNAME: ${{ secrets.CW_USERNAME }}
      CW_PASSWORD: ${{ secrets.CW_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright test
        run: node all.js

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

      - name: Upload temp reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-temp
          path: report-temp/

      - name: Upload final html reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-final
          path: report-final/
      
            - name: Upload JSON report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: json-report
          path: playwright-report/results.json